### ISSUE TITLE
Recoding step between target data and base data

### ISSUE THREAD

**Issue by fitbio** [choishingwan/PRS-Tutorial#1]
Dear Developer,

First of all thank you very much for the brief introduction to PRS tutorial. I have a small quesion related to the recoding step in R when we check for mismatching genotypes between base and target data. 

There were two codes
info.recode 
info.crecode

However I see the steps for info.crecode further continues using complement function, but steps for info.recode data remains empty. So should I recode the data, or leave as it is?

**Comment by choishingwan** [comment]
You will need those data structure in later steps. In the [mismatch SNP section ](https://choishingwan.github.io/PRS-Tutorial/target/#35-mismatching-genotypes), as a large number of steps are required, we separated them out into individual component as much as possible, but I guess the info.recode code should be located in step 4 instead of step 3 for clarity.
