### ISSUE TITLE
'y.col' and 'ind.col' should have the same length.

### ISSUE THREAD

**Issue by Sandyyy123** [choishingwan/PRS-Tutorial#32]
```R
pred_inf <- NULL
for(chr in 1:22){
  obj.bigSNP <- snp_attach(paste0("courage_eur.qc01_chr",chr,".rds"))
  genotype <- obj.bigSNP$genotypes
  # calculate PRS for all samples
  ind.test <- 1:nrow(genotype)
  # Extract SNPs in this chromosome
  chr.idx <- which(info_snp$chr == chr)
  ind.chr <- info_snp$`_NUM_ID_`[chr.idx]
  tmp <- big_prodVec(genotype,
                     beta_inf,
                     ind.row = ind.test,
                     ind.col = ind.chr)
  if(is.null(pred_inf)){
    pred_inf <- tmp
  }else{
    pred_inf <- pred_inf + tmp
  }
}



```

**Comment by Sandyyy123** [comment]
Tried  beta_inf[ind.chr], which worked. But, I am not sure, if its the correct way as it didnt work for other models.

**Comment by choishingwan** [comment]
it might be helpful if you can combine the three issues and let me know what exactly goes wrong, e.g. the error messages etc. 

Also, the tutorial on LDpred was on version 1.4.7, which might have changed quite a bit since I last updated the script. So if it is more of an LDpred2 issue, I'd suggest you to consult their authors instead
